spring:
  datasource:
    url: 
    username: 
    password: 
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
  mail:
    host: 
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: 
          starttls:
            enable: 
          connectiontimeout: 
          timeout: 
          writetimeout: 
#  jpa: 
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  mybatis:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package: com.football.domain
  devtools:
    restart:
      enabled: false
      
springdoc:
  api-docs:
    path: /api-docs  # API 문서 경로
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접근 경로
    operations-sorter: alpha  # API 정렬 방식 (알파벳순)
    tags-sorter: alpha  # 태그 정렬 방식 (알파벳순)
